MTDSA-8287 List Charges Alignments
hmrc/self-assessment-accounts-api pull request #165
Opened 2021-03-08 09:18 UTC by ngangaNjiraini

2021-03-08 16:16 UTC, BetaDraconis requested changes
`INVALID_INCLUDE_STATISTICAL`, `INVALID_REQUEST`, and `INVALID_DATE_RANGE` service error mappings are missing

2021-03-08 16:17 UTC, BetaDraconis commented on app/v1/models/response/listCharges/ListChargesResponse.scala
>  object ListChargesResponse extends HateoasLinks {
This file is also missing a Writes test

2021-03-11 10:26 UTC, Taiwo-AB commented on app/config/DocumentationController.scala
> +import uk.gov.hmrc.play.bootstrap.controller.BackendController
Can you please revert back to use previous import as this import is deprecated. Info can be seen [here](https://github.com/hmrc/bootstrap-play/blob/master/bootstrap-backend-play-26/src/main/scala/uk/gov/hmrc/play/bootstrap/package.scala#L37)

2021-03-11 10:27 UTC, Taiwo-AB commented on app/v1/connectors/ListChargesConnector.scala
> +import uk.gov.hmrc.play.bootstrap.http.HttpClient
Can you please revert back to use previous import as this import is deprecated. Info can be seen [here](https://github.com/hmrc/bootstrap-play/blob/master/bootstrap-backend-play-26/src/main/scala/uk/gov/hmrc/play/bootstrap/package.scala#L89)

2021-03-11 10:27 UTC, Taiwo-AB commented on app/v1/models/errors/mtdErrors.scala
>  object NoChargesFoundError extends MtdError("NO_CHARGES_FOUND", "No charges found")
This should be removed as it is not used.

2021-03-11 10:27 UTC, Taiwo-AB commented on app/v1/models/errors/mtdErrors.scala
> +object NoTransactionsFoundError extends MtdError("NO_TRANSACTIONS_FOUND", "No transactions found")
This should also be removed as it is not used

2021-03-11 10:27 UTC, Taiwo-AB commented on test/v1/controllers/ListChargesControllerSpec.scala
>        )
Unused import here

2021-03-11 10:28 UTC, Taiwo-AB commented on test/v1/fixtures/ListChargesFixture.scala
>    val fullDesChargeResponse: JsValue = Json.parse(
minimalDesChargeResponse and fullDesListChargesSingleResponse can be removed here as they are not currently being used

2021-03-11 10:28 UTC, Taiwo-AB commented on test/v1/fixtures/ListChargesFixture.scala
>      s"""
The s can be removed here

2021-03-11 10:31 UTC, Taiwo-AB commented on app/v1/controllers/AuthorisedController.scala
> +import uk.gov.hmrc.play.bootstrap.controller.BackendController
Can you please revert back to use previous import as this import is deprecated. Info can be seen [here](https://github.com/hmrc/bootstrap-play/blob/master/bootstrap-backend-play-26/src/main/scala/uk/gov/hmrc/play/bootstrap/package.scala#L37)

2021-03-11 13:48 UTC, merged