MTDSA-8977 Retrieve coding out RAML draft
hmrc/self-assessment-accounts-api pull request #185
Opened 2021-05-07 16:10 UTC by RachGibbons

2021-05-10 08:17 UTC, HarryBaxter commented on resources/public/api/conf/1.0/retrieveCodingOutUnderpayments.raml
> +  - headers.contentTypeJson
Won't need contentTypeJson as its a GET

2021-05-12 12:00 UTC, BetaDraconis commented on resources/public/api/conf/1.0/queryParameters.raml
> +      to:
this should be `source`

2021-05-12 12:00 UTC, BetaDraconis commented on resources/public/api/conf/1.0/queryParameters.raml
> +  view:
also this

2021-05-12 12:07 UTC, BetaDraconis commented on resources/public/api/conf/1.0/queryParameters.raml
> +        description: 'The type of business the loss applies to. Limited to the following possible values: <b><ul><li>`hmrcHeld`<li>`user`<li>`latest`</b>'
This description isn't correct

2021-05-12 13:30 UTC, BetaDraconis requested changes

2021-05-12 13:30 UTC, BetaDraconis commented on resources/public/api/conf/1.0/examples/retrieveCodingOutUnderpayments/retrieve_coding_out_underpayments_response.json
> +  "taxCodeComponents": {
this object doesn't appear on the response to vendors

2021-05-12 13:30 UTC, BetaDraconis commented on resources/public/api/conf/1.0/examples/retrieveCodingOutUnderpayments/retrieve_coding_out_underpayments_response.json
> +        "rel": "create-and-amend-coding-out-underpayments"
```suggestion
        "rel": "create-or-amend-coding-out-underpayments"
```

2021-05-12 13:30 UTC, BetaDraconis commented on resources/public/api/conf/1.0/errors.raml
>              type: types.errorResponse
The error descriptions in this file are quite old. Can you update them to match the spec for retrieve coding out underpayments please?

2021-05-12 13:30 UTC, BetaDraconis commented on resources/public/api/conf/1.0/schemas/retrieve_coding_out_underpayments_response.json
> +    },
```suggestion
"selfAssessmentUnderPayments": {
      "type": "array",
      "description": "Array containing details of coding out Self Assessment underpayments.",
      "items": {
        "type": "object",
        "properties": {
          "amount": {
            "description": "The total coding out amount attributed to Self Assessment underpayments. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "multipleOf": 0.01,
            "minimum": 0.00,
            "maximum": 99999999999.99,
            "example": "5000.99"
          },
          "relatedTaxYear": {
            "description": "The tax year related to the underpayment.",
            "type": "string",
            "example": "2021-22"
          },
          "submittedOn": {
            "description": "The date the coding out information was added. It is either the latest change date held within HMRC or the latest user submitted date. It is in the format YYYY-MM-DDThh:mm:ssZ.",
            "type": "string",
            "example": "2020-07-06T09:37:17Z"
          }
        },
        "required": [
          "amount",
          "relatedTaxYear",
          "submittedOn"
        ]
      }
    },
```

For the array fields to show up properly in the RAML they need to be within a "properties" object like this. They should also be mandatory I think according to the spec. This applies to all of the arrays in this schema.

2021-05-12 13:31 UTC, BetaDraconis commented on resources/public/api/conf/1.0/schemas/retrieve_coding_out_underpayments_response.json
> +    }
HATEOAS links also need to be included here, like: https://github.com/hmrc/self-assessment-accounts-api/blob/a52324a272af32544fe7fa9da3b635bf5153c8f1/resources/public/api/conf/1.0/schemas/create_or_amend_coding_out_underpayments_response.json#L7

2021-05-12 15:52 UTC, merged