[MTDSA-8979] Retrieve Models and Errors
hmrc/self-assessment-accounts-api pull request #191
Opened 2021-05-12 14:41 UTC by Nboaram

2021-05-13 08:45 UTC, Taiwo-AB commented on app/v1/models/request/retrieveCodingOut/RetrieveCodingOutParsedRequest.scala
> +case class RetrieveCodingOutParsedRequest(nino: Nino, taxYear: String, source: String)
source should be optional

2021-05-13 08:45 UTC, Taiwo-AB commented on app/v1/models/request/retrieveCodingOut/RetrieveCodingOutRawRequest.scala
> +case class RetrieveCodingOutRawRequest(nino: String, taxYear: String, source: String) extends RawData
source should be optional

2021-05-13 08:47 UTC, Taiwo-AB commented on app/v1/models/response/retrieveCodingOut/ResponseItem.scala
> +
Can use OFormat

2021-05-13 08:49 UTC, Taiwo-AB commented on app/v1/models/response/retrieveCodingOut/RetrieveCodingOutResponse.scala
> +                                     taxCodeComponents: TaxCodeComponents)
This needs to be updated as there is no object called taxCodeComponents

2021-05-13 08:53 UTC, Taiwo-AB commented on test/v1/models/response/retrieveCodingOut/RetrieveCodingOutResponseSpec.scala
> +  val mtdResponse: JsValue = Json.parse(
This would need updating as no object called taxCodeComponents

2021-05-13 08:57 UTC, Taiwo-AB commented on app/v1/models/domain/MtdSource.scala
> +
Needs to be converted to downstream source

2021-05-13 08:57 UTC, Taiwo-AB commented on app/v1/models/domain/DownstreamSource.scala
> +  }
This needs `LATEST`

2021-05-13 14:49 UTC, BetaDraconis requested changes

2021-05-13 14:49 UTC, BetaDraconis commented on app/v1/models/domain/DownstreamSource.scala
> +  }
I think I would rather remove these and allow the API to return a 500 than using a dummy string like this

2021-05-13 14:49 UTC, BetaDraconis commented on app/v1/models/domain/DownstreamSource.scala
> +  }
I think I would rather remove these and allow the API to return a 500 than using a dummy string like this

2021-05-13 14:49 UTC, BetaDraconis commented on app/v1/models/response/retrieveCodingOut/RetrieveCodingOutResponse.scala
> +
Can we remove these extra lines

2021-05-13 14:49 UTC, BetaDraconis commented on test/v1/models/domain/DownstreamSourceSpec.scala
> +      DownstreamSource.`HMRC-HELD`.toMtdSource shouldBe "Invalid Source Response"
-->

2021-05-13 14:49 UTC, BetaDraconis commented on test/v1/models/domain/DownstreamSourceSpec.scala
> +      DownstreamSource.`LATEST`.toMtdSource shouldBe "Invalid Source Response"
-->

2021-05-13 14:49 UTC, BetaDraconis commented on test/v1/models/domain/DownstreamSourceSpec.scala
> +    ("HMRC-HELD", `HMRC-HELD`),
-->

2021-05-13 14:49 UTC, BetaDraconis commented on test/v1/models/domain/DownstreamSourceSpec.scala
> +    ("LATEST", `LATEST`)
-->

2021-05-13 14:49 UTC, BetaDraconis commented on test/v1/models/response/retrieveCodingOut/ResponseItemSpec.scala
> +
Some extra lines here as well

2021-05-13 14:49 UTC, BetaDraconis commented on test/v1/models/response/retrieveCodingOut/ResponseItemSpec.scala
> +
Some extra lines here as well

2021-05-13 15:07 UTC, Nboaram commented on app/v1/models/domain/DownstreamSource.scala
> +  }
This is now strings, but I believe in this direction you "can" specify latest although it is the default if nothing is sent.

But you can't get it on the way back from so this now just reads "Invalid Source Response"

2021-05-13 15:08 UTC, Nboaram commented on app/v1/models/response/retrieveCodingOut/ResponseItem.scala
> +}
It could now be something like "taxCodeComponent"?

2021-05-13 15:19 UTC, BetaDraconis commented on app/v1/models/domain/DownstreamSource.scala
> +  }
could it not just be removed?

2021-05-13 15:20 UTC, BetaDraconis commented on app/v1/models/response/retrieveCodingOut/ResponseItem.scala
> +}
sure, sounds good

2021-05-14 09:32 UTC, BetaDraconis approved these changes

2021-05-14 09:32 UTC, merged